### ISSUE TITLE
Clicking on an article in the blog roll doesn't load the post

### ISSUE THREAD

**Issue by jcayzac** [rodneylab/sveltekit-blog-mdx#1]
Clicking on an article in the blog roll doesn't load the post, only a yellow contact card and another blog roll.

Steps to reproduce the behaviour:

1. `pnpm i`
2. `pnpm run dev`
3. Open http://localhost:3000 in the browser
4. Click on any post

Expected behaviour: the content of the post is shown.

- OS: macOS
- Browser: Chrome
- Version: 91

**Comment by jcayzac** [comment]
By adding a `/` at the end of a post URL, e.g. http://localhost:3000/best-medium-format-camera-for-starting-out/ , I can obtain the following error message:

```
ImgixClient must be passed a valid string domain
Error: ImgixClient must be passed a valid string domain
    at new ImgixClient (/Users/julien.cayzac/Desktop/sveltekit-blog-mdx/node_modules/.pnpm/@imgix+js-core@3.2.1/node_modules/@imgix/js-core/dist/index.cjs.js:245:13)
    at BlogPost.svelte:11:21
    at Object.$$render (/Users/julien.cayzac/Desktop/sveltekit-blog-mdx/node_modules/.pnpm/svelte@3.40.1/node_modules/svelte/internal/index.js:1670:22)
    at eval (/Users/julien.cayzac/Desktop/sveltekit-blog-mdx/src/routes/__layout.svelte:101:92)
    at Object.$$render (/Users/julien.cayzac/Desktop/sveltekit-blog-mdx/node_modules/.pnpm/svelte@3.40.1/node_modules/svelte/internal/index.js:1670:22)
    at root.svelte:36:44
    at $$render (/Users/julien.cayzac/Desktop/sveltekit-blog-mdx/node_modules/.pnpm/svelte@3.40.1/node_modules/svelte/internal/index.js:1670:22)
    at Object.render (/Users/julien.cayzac/Desktop/sveltekit-blog-mdx/node_modules/.pnpm/svelte@3.40.1/node_modules/svelte/internal/index.js:1678:26)
    at render_response (file:///Users/julien.cayzac/Desktop/sveltekit-blog-mdx/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.136_svelte@3.40.1/node_modules/@sveltejs/kit/dist/ssr.js:379:28)
    at async respond_with_error (file:///Users/julien.cayzac/Desktop/sveltekit-blog-mdx/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.136_svelte@3.40.1/node_modules/@sveltejs/kit/dist/ssr.js:999:10)
```

**Comment by jcayzac** [comment]
Removing all references and uses of Imgix fixes everything.

**Comment by rodneylab** [comment]
@jcayzac glad you sorted this out. The code uses Imgix to generate responsive images in NextGen formats.  I see how this can be confusing if you want to clone and have it work straight off, especially if you don't already have an Imgix account.  I am looking at alternatives for responsive image generation without an external service and will update the code when I have something I am happy with.  In the meantime I will update the docs to make things clearer. Hope that helps. Rodney

**Comment by rodneylab** [comment]
Just updated. Included static images (not responsive or in NextGen formats) in the repo which are used so the repo works out of the box with no Imgix credentials.

**Comment by jcayzac** [comment]
> @jcayzac glad you sorted this out. The code uses Imgix to generate responsive images in NextGen formats. I see how this can be confusing if you want to clone and have it work straight off, especially if you don't already have an Imgix account. I am looking at alternatives for responsive image generation without an external service and will update the code when I have something I am happy with. In the meantime I will update the docs to make things clearer. Hope that helps. Rodney

FWIW I got vite-imagetools to work pretty quickly and I really dig it. I have it generate a `srcset` prop for my components and also from a rehype plugin I use with mdsvex.
