### ISSUE TITLE
Error: request in handle has been replaced with event. See https://github.com/sveltejs/kit/pull/3384 for details

### ISSUE THREAD

**Issue by magick93** [rodneylab/sveltekit-blog-mdx#3]
**Describe the bug**
Running in VS Code dev containers, I'm getting the following error:

```
request in handle has been replaced with event. See https://github.com/sveltejs/kit/pull/3384 for details
Error: request in handle has been replaced with event. See https://github.com/sveltejs/kit/pull/3384 for details
    at Object.get request [as request] (file:///workspaces/sveltekit-blog-mdx/node_modules/@sveltejs/kit/dist/chunks/index.js:1678:11)
    at Object.handle (//workspaces/sveltekit-blog-mdx/src/hooks:69:32)
    at respond (file:///workspaces/sveltekit-blog-mdx/node_modules/@sveltejs/kit/dist/chunks/index.js:1585:30)
    at file:///workspaces/sveltekit-blog-mdx/node_modules/@sveltejs/kit/dist/chunks/index.js:1910:30
```

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to [open.vscode.dev/rodneylab/sveltekit-blog-mdx](https://open.vscode.dev/rodneylab/sveltekit-blog-mdx)
2. Run through various setup options, which I cant recall now
4. Run `npm install`
5. Run `pm run dev`

**Expected behaviour**

Expect the web project would be build and run without errors

**Additional context**

# Error output

```
request in handle has been replaced with event. See https://github.com/sveltejs/kit/pull/3384 for details
Error: request in handle has been replaced with event. See https://github.com/sveltejs/kit/pull/3384 for details
    at Object.get request [as request] (file:///workspaces/sveltekit-blog-mdx/node_modules/@sveltejs/kit/dist/chunks/index.js:1678:11)
    at Object.handle (//workspaces/sveltekit-blog-mdx/src/hooks:69:32)
    at respond (file:///workspaces/sveltekit-blog-mdx/node_modules/@sveltejs/kit/dist/chunks/index.js:1585:30)
    at file:///workspaces/sveltekit-blog-mdx/node_modules/@sveltejs/kit/dist/chunks/index.js:1910:30
```

**Comment by rodneylab** [comment]
Hi @magick93 thanks for reaching out.  There were breaking changes in a recent release of SvelteKit and when you install the repo, you get the current latest version.  There's a couple of solutions:


- if you need to use the static adapter (default in the repo), unfortunately it hasn't yet been updated for the breaking changes so you could roll back your SvelteKit version to `1.0.0-next.230`:

```shell
    pnpm add -D @sveltejs/kit@1.0.0-next.230
```

- if you do not need adapter static, change out the adapter for one which has been updated and replace the `handle` function in src/hooks.js:

```javascript
export async function handle({ event, resolve }) {
  const response = await resolve(event);
  response.headers.set('X-Frame-Options', 'SAMEORIGIN');
  response.headers.set('Referrer-Policy', 'no-referrer');
  response.headers.set(
    'Permissions-Policy',
    'accelerometer=(), autoplay=(), camera=(), document-domain=(), encrypted-media=(), fullscreen=(), gyroscope=(), interest-cohort=(), magnetometer=(), microphone=(), midi=(), payment=(), picture-in-picture=(), publickey-credentials-get=(), sync-xhr=(), usb=(), xr-spatial-tracking=(), geolocation=()',
  );
  response.headers.set('X-Content-Type-Options', 'nosniff');
  /* Switch from Content-Security-Policy-Report-Only to Content-Security-Policy once you are satisifed policy is what you want
   * on switch comment out the Report-Only line
   */
  response.headers.set('Content-Security-Policy-Report-Only', csp);
  // response.headers.set('Content-Security-Policy', csp);
  response.headers.set('Strict-Transport-Security', 'max-age=31536000; includeSubDomains; preload');
  response.headers.set(
    'Expect-CT',
    `max-age=86400, report-uri="https://sentry.io/api/${
      import.meta.env.VITE_SENTRY_PROJECT_ID
    }/security/?sentry_key=${import.meta.env.VITE_SENTRY_KEY}"`,
  );
  response.headers.set(
    'Report-To',
    `{group: "csp-endpoint", "max_age": 10886400, "endpoints": [{"url": "https://sentry.io/api/${
      import.meta.env.VITE_SENTRY_PROJECT_ID
    }/security/?sentry_key=${import.meta.env.VITE_SENTRY_KEY}"}]}`,
  );
  return response;
}
```
I'll update the repo once the static adapter is updated.  Let me know these options work for you.

Thanks,
Rodney

**Comment by rodneylab** [comment]
Repo is updated and working with latest verion of SvelteKit now. Let me know if you are still seeing issues after pulling latest repo.
